app:
  name: 'SDI CC Report 2023'
  title: 'SDI CC Report 2023'
  # width: 500
  # height: 800
  # theme: 'breeze' # values: 'adapta', 'aquativo', 'arc', 'black', 'blue', 'breeze', 'clearlooks', 'elegance', 'equilux', 'itft1', 'keramik', 'kroc', 'plastik', 'radiance', 'scid themes', 'smog', 'winxpblue'
  # device: 'desktop' # values: 'desktop', 'mobile'

locales:
    directory: './sdi_cc_report/locales/'
    lang: 'fr'

history:
  file: './sdi_cc_report/data/.history'
  clear_on_exit: False

cli:
  prompt: '>'

log:
  log_file: './sdi_cc_report/data/.log'

dashboard:
  dashboard_directory: './sdi_cc_report/dashboard/'
  templates_directory: './sdi_cc_report/dashboard/templates/'
  destination_directory: './sdi_cc_report/dashboard/'

reports:
  - name: WMS DataGrandEst
    type: wms
    url: 'https://www.datagrandest.fr/public/wms-report.log'
  - name: WFS DataGrandEst
    type: wfs
    url: 'https://www.datagrandest.fr/public/wfs-report.log'
  - name: CSW DataGrandEst
    type: csw
    url: 'https://www.datagrandest.fr/public/csw-report.log'

requests:
  ssl_verify: False

web:
  server_host: '127.0.0.1'
  server_port: '8001'
  ui_host: '127.0.0.1'
  ui_port: '8001'
  width: 400
  height: 800